<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\AuthorizationLink $block */

$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="authorization-link" data-label="<?= $block->escapeHtmlAttr(__('or')) ?>">
    <a <?= /* @noEscape */
    $block->getLinkAttributes() ?><?= /* @noEscape */
    $dataPostParam ?>>
        <?php
        //              echo  $block->escapeHtml($block->getLabel())
        ?>
        <img class="sign-image-container" src="<?= $block->escapeHtml($block->getImage()) ?>" alt="sign in"/>
    </a>
</li>
