<?php
$productCollection = $block->getProductCollection()->toArray();
$products = $block->getProductCollection();
$productUrls = [];
$productCategoryId = [];
//$productId = 10;  //product id
//$category = $block->getCategoryIds($productId);
//var_dump($category);
foreach ($products as $product) {
//    echo 'next: ';
    $productId = $product->getData("entity_id");
//    $categoryId = $product->getCategoryIds();
//    var_dump($categoryId[0]);
//    if ($categoryIds = $product->getCustomAttribute('category_ids')) {
//        foreach ($categoryIds->getValue() as $categoryId) {
//            $category = $this->categoryRepository->get($categoryId);
//            echo($category);
//        }
//    }
    $category = $block->getCategoryIds($productId);
    $productCategoryId[] = $category[1];
//    echo $category[1];
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $productt = $objectManager->create('Magento\Catalog\Model\Product')->load($productId);
    $addToCartUrl = $objectManager->get('Magento\Checkout\Helper\Cart')->getAddUrl($productt);
    $productUrls[] = $addToCartUrl;

}
$productConf = $block->getProductConfigurable();
foreach ($productConf as $product) {
    $_children = $product->getTypeInstance()->getUsedProducts($product);
//    echo '<pre>', var_dump($product->getOptions()), '</pre>';
}
//$colorOptions = [];
//$sizeOptions = [];
$options = [];
foreach ($_children as $child) {
//    $colorOptions[] = $child->getColor();
//    $sizeOptions[] = $child->getSize();
    $parentId = '';
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $product = $objectManager->create('Magento\ConfigurableProduct\Model\ResourceModel\Product\Type\Configurable')->getParentIdsByChild($child->getId());
    if (isset($product[0])) {
        $parentId = $product[0];
    }
    $options[] = array("color" => $child->getColor(),
        "size" => $child->getSize(),
        "id" => $child->getId(),
        "parentId" => $parentId);
//    echo '<pre>', var_dump($child->toArray()), '</pre>';
}

//echo '<pre>', var_dump($colorOptions), '</pre>';
//echo '<pre>', var_dump($sizeOptions), '</pre>';
//echo '<pre>', var_dump($options), '</pre>';
//echo "dadad";
//$dataaa = $this->scopeConfig->getValue('samplemodule/general/display_text', \Magento\Store\Model\ScopeInterface::SCOPE_STORE);
$display_title = $block->getConfigValue('samplemodule/general/display_title');
$display_text = $block->getConfigValue('samplemodule/general/display_text');

//echo $configValue;
// print current category data
//echo "ebwfuygeierwc";
//if ($currentCategory = $block->getCurrentCategory()) {
//    echo $currentCategory->getName() . '<br />';
//    echo $currentCategory->getId() . '<br />';
//}
?>

<!--<script type="application/javascript">-->
<!--    require([-->
<!--        'jquery',-->
<!--        'jquery/jquery.cookie'-->
<!--    ], function ($) {-->
<!--        'use strict';-->
<!--        $(document).ready(function () {-->
<!---->
<!--        });-->
<!--    });-->
<!--</script>-->

<div id="custom-component" data-bind="scope:'customcomponent'">
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
    {
        "#custom-component": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "customcomponent": {
                        "component": "Custom_SampleModule/js/custom-component",
                        "items": <?php echo json_encode($productCollection); ?>,
                        "itemUrls": <?php echo json_encode($productUrls); ?>,
                        "itemCategoryId": <?php echo json_encode($productCategoryId); ?>,
                        "options": <?php echo json_encode($options); ?>,
                        "title": <?php echo json_encode($display_title); ?>,
                        "text": <?php echo json_encode($display_text); ?>
                    }
                }
            }
        }
    }















    </script>
</div>


